// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgLqr7u6qVbhe67chSVvVCv_hMnAhxCcQ',
    appId: '1:555596740611:web:527bb0613c64eb27f4f636',
    messagingSenderId: '555596740611',
    projectId: 'sidm-project',
    authDomain: 'sidm-project.firebaseapp.com',
    storageBucket: 'sidm-project.appspot.com',
    measurementId: 'G-BL4VWB9ZGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAq6GSjj28LTPivZl5PFj0UI-pOppL72M',
    appId: '1:555596740611:android:cb7ba73277cb96cbf4f636',
    messagingSenderId: '555596740611',
    projectId: 'sidm-project',
    storageBucket: 'sidm-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf0FDW1uBYscTahV57kErk7LchBLTLE9o',
    appId: '1:555596740611:ios:4fe9acd553a965eef4f636',
    messagingSenderId: '555596740611',
    projectId: 'sidm-project',
    storageBucket: 'sidm-project.appspot.com',
    iosBundleId: 'com.syncfusion.flutterExamples',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf0FDW1uBYscTahV57kErk7LchBLTLE9o',
    appId: '1:555596740611:ios:4fe9acd553a965eef4f636',
    messagingSenderId: '555596740611',
    projectId: 'sidm-project',
    storageBucket: 'sidm-project.appspot.com',
    iosBundleId: 'com.syncfusion.flutterExamples',
  );
}
